export type StageCopy = ReturnType<typeof getStageCopy>

const zh = {
  cast: {
    active: '当前回复',
    empty: '当前没有激活角色。',
    sessionCharacterBadge: '临时角色',
    section: '当前参与角色',
  },
  characterDialog: {
    details: '详情',
    variables: '变量',
    variablesDescription: '查看并编辑当前角色在这场会话中的角色变量。',
  },
  sessionCharacterDialog: {
    delete: '删除角色',
    deleting: '正在删除...',
    details: '临时角色详情',
    displayName: '显示名称',
    enterScene: '加入当前场景',
    inScene: '当前在场',
    leaveScene: '移出当前场景',
    personality: '性格',
    save: '保存修改',
    saved: '临时角色已更新。',
    saving: '正在保存...',
    sectionPrompt: 'System Prompt',
    style: '说话风格',
    title: '临时角色',
    updated: '最近更新',
  },
  composer: {
    cancelSuggestions: '关闭建议',
    placeholder: '输入玩家行动或对白，发起下一轮...',
    running: '正在演出...',
    send: '发起回合',
    suggestions: '回复建议',
    suggestionsDescription: '打开后，每轮结束都会自动生成新的回复建议。',
    suggestionsEmpty: '还没有回复建议。',
    suggestionsGenerate: '生成回复建议',
    suggestionsLoading: '正在生成回复建议...',
    suggestionsUnavailable: '本回合进行中，暂时不能生成回复建议。',
  },
  createSession: {
    apiGroup: 'API 组',
    apiGroupPlaceholder: '选择一个 API 组',
    cancel: '取消',
    configureApis: '前往 API 管理',
    configureApiGroups: '前往 API 管理',
    configurePresets: '前往预设',
    create: '创建会话',
    creating: '正在创建...',
    displayName: '会话名称',
    emptyApis: '还没有可用的 API，请先创建至少一条可复用的连接配置。',
    emptyApiGroups: '还没有可用的 API 组，请先把 API 绑定成一组可复用配置。',
    emptyPlayerProfiles: '当前没有玩家档案，可直接创建空档案会话。',
    emptyPresets: '还没有可用预设，请先创建一套预设。',
    emptyStories: '还没有可用的故事，请先在工作台生成故事。',
    playerProfile: '玩家档案',
    preset: '预设',
    presetPlaceholder: '选择一个预设',
    story: '故事',
    title: '新建会话',
  },
  deleteSession: {
    confirm: '删除会话',
    deleting: '正在删除...',
    message: '确定要删除这场会话吗？这个操作不能撤回。',
    title: '删除会话',
  },
  editSession: '编辑会话',
  empty: {
    stage: '从左侧选择一场会话，或者直接新建一场。',
  },
  intro: {
    collapse: '收起介绍',
    empty: '当前故事还没有介绍。',
    expand: '展开介绍',
    section: '当前 story 介绍',
  },
  commonVariables: {
    empty: '当前没有可展示的常用变量。',
    section: '变量',
  },
  list: {
    empty: '还没有会话。',
    refresh: '刷新会话',
    section: '会话列表',
    subtitle: '切换与新建会话。',
    untitledStory: '未命名故事',
  },
  messages: {
    action: '动作',
    cancelEditPlayer: '取消',
    deletePlayer: '删除这条输入',
    editPlayer: '编辑这条输入',
    expandThought: '查看思考',
    narrator: '旁白',
    noMessages: '这场会话还没有历史记录。',
    player: '玩家',
    savePlayer: '保存修改',
    thinking: '思考',
  },
  notice: {
    apiResourcesFailed: '加载 API 资源失败。',
    createFailed: '创建会话失败。',
    created: '会话已创建。',
    deleteFailed: '删除会话失败。',
    deleted: '会话已删除。',
    listFailed: '加载会话列表失败。',
    messageDeleteFailed: '删除消息失败。',
    messageUpdateFailed: '保存消息修改失败。',
    playerDescriptionFailed: '保存玩家描述失败。',
    playerDescriptionSaved: '玩家描述已更新。',
    playerProfilesFailed: '加载玩家档案失败。',
    playerProfileFailed: '切换玩家档案失败。',
    playerProfileSaved: '玩家档案已更新。',
    runFailed: '发起回合失败。',
    sessionCharacterDeleteFailed: '删除临时角色失败。',
    sessionCharacterEnterFailed: '加入当前场景失败。',
    sessionCharacterLeaveFailed: '移出当前场景失败。',
    sessionCharacterLoadFailed: '加载临时角色失败。',
    sessionCharacterSaved: '临时角色已更新。',
    sessionCharacterUpdateFailed: '保存临时角色失败。',
    sessionConfigSaved: '会话设置已更新。',
    sessionLoadFailed: '加载会话详情失败。',
    sessionRenameFailed: '修改会话名称失败。',
    sessionRenamed: '会话名称已更新。',
    snapshotRefreshFailed: '刷新运行时快照失败。',
    snapshotRefreshed: '运行时快照已刷新。',
    storiesFailed: '加载故事列表失败。',
    suggestRepliesFailed: '生成回复建议失败。',
    updateConfigFailed: '保存会话设置失败。',
  },
  rail: {
    cast: '查看参与角色',
    intro: '查看故事介绍',
    status: '查看状态',
    subtitle: 'story、状态与角色。',
    variables: '查看变量',
  },
  renameSession: {
    cancel: '取消',
    displayName: '会话名称',
    errors: {
      displayNameRequired: '请填写会话名称。',
    },
    placeholder: '新的会话名称',
    save: '保存名称',
    saving: '正在保存...',
    sessionId: '会话 ID',
    title: '修改会话名称',
  },
  settings: {
    bindings: {
      apiGroup: 'API 组',
      apiGroupPlaceholder: '选择 API 组',
      currentApiGroup: '当前 API 组',
      currentPreset: '当前预设',
      description: '为当前会话绑定一组可执行接口和一套生成参数预设。',
      errors: {
        apiGroupRequired: '请先选择 API 组。',
        presetRequired: '请先选择预设。',
      },
      missing: '未找到，请重新选择',
      preset: '预设',
      presetPlaceholder: '选择预设',
      save: '保存会话设置',
      saving: '正在保存...',
      section: '会话绑定',
    },
    description: '在这里调整当前会话的 API 组、预设、玩家档案和运行时状态。',
    playerDescription: {
      description: '直接覆盖当前会话使用的玩家描述，并清空当前玩家档案绑定。',
      errors: {
        required: '请填写玩家描述。',
      },
      placeholder: '输入当前会话要使用的玩家描述...',
      save: '保存玩家描述',
      saving: '正在保存...',
      section: '玩家描述',
    },
    playerProfile: {
      description: '切换当前会话绑定的玩家档案。切换不会改变已有 player_state。',
      label: '玩家档案',
      noProfile: '不绑定玩家档案',
      noProfileHint: '当前未绑定玩家档案，会直接使用手动玩家描述。',
      placeholder: '选择一个玩家档案',
      preview: '当前档案说明',
      save: '应用玩家档案',
      saving: '正在应用...',
      section: '玩家档案',
    },
    sessionCharacters: {
      delete: '删除',
      description: '管理这场会话里由导演临时引入的运行时角色。',
      empty: '这场会话里还没有临时角色。',
      enterScene: '加入场景',
      inScene: '在场',
      leaveScene: '移出场景',
      outOfScene: '离场',
      section: '临时角色',
      view: '查看与编辑',
    },
    snapshot: {
      activeCharacters: '激活角色',
      currentNode: '当前节点',
      description: '读取当前会话最新的运行时快照，确认状态是否已经同步。',
      playerDescription: '当前玩家描述',
      playerStateKeys: '玩家状态字段',
      refresh: '刷新快照',
      section: '运行时快照',
      turnIndex: '当前回合',
    },
    title: '会话设置',
  },
  stage: {
    subtitle: '选择或新建会话。',
    title: '舞台',
  },
  statusBar: {
    actor: '{name} 正在回复',
    director: '导演正在安排演出',
    narrator: '叙述者正在组织旁白',
    recordingInput: '守秘人正在记录输入',
    suggestingReplies: '回复者正在生成建议',
    updatingState: '守秘人正在同步状态',
  },
  storyNode: {
    collapse: '收起详情',
    expand: '查看全部',
    goal: '当前目标',
    nodeId: '节点 ID',
    scene: '当前场景',
    section: '状态',
  },
  tabs: {
    dialogue: '对话',
    settings: '设置',
    variables: '变量',
  },
  time: {
    unknown: '未记录时间',
  },
  variables: {
    addCharacterGroup: '新增角色变量',
    addRow: '新增变量',
    characterHint: '角色 ID',
    characterState: '角色变量',
    conditions: {
      currentValue: '当前值',
      empty: '当前节点没有后续跳转。',
      invalid: '条件格式暂不可读。',
      missing: '缺少变量',
      noCondition: '无条件跳转',
      scopeCharacter: '角色变量',
      scopeCustom: '自定义变量',
      scopePlayer: '玩家变量',
      section: '节点跳转条件',
      satisfied: '已满足',
      target: '目标节点',
      unsatisfied: '未满足',
    },
    custom: '自定义变量',
    empty: '先在左侧选择一场会话，再查看变量。',
    errors: {
      duplicateKey: '变量名不能重复。',
      invalidJson: '请输入合法的 JSON。',
      keyRequired: '请填写变量名。',
    },
    hasExternalUpdates: '运行时状态已更新。你当前还有未保存改动，可手动刷新变量。',
    json: '值（JSON）',
    key: '变量名',
    operator: '运算符',
    playerState: '玩家变量',
    refresh: '刷新变量',
    reset: '重置改动',
    save: '保存修改',
    saved: '变量已更新。',
    saveFailed: '保存变量失败。',
    saving: '正在保存...',
    sectionDescription: '查看当前会话里的自定义变量、玩家变量，并核对节点跳转条件。',
    title: '变量管理',
    value: '目标值',
    variableLoadFailed: '加载变量失败。',
  },
} as const

const en = {
  cast: {
    active: 'Replying now',
    empty: 'No active cast is available right now.',
    sessionCharacterBadge: 'Session',
    section: 'Active Cast',
  },
  characterDialog: {
    details: 'Details',
    variables: 'Variables',
    variablesDescription: 'Inspect and edit the character-specific state attached to this session.',
  },
  sessionCharacterDialog: {
    delete: 'Delete Character',
    deleting: 'Deleting...',
    details: 'Temporary Character Details',
    displayName: 'Display Name',
    enterScene: 'Enter Scene',
    inScene: 'Currently in Scene',
    leaveScene: 'Leave Scene',
    personality: 'Personality',
    save: 'Save Changes',
    saved: 'Temporary character updated.',
    saving: 'Saving...',
    sectionPrompt: 'System Prompt',
    style: 'Style',
    title: 'Temporary Character',
    updated: 'Updated',
  },
  composer: {
    cancelSuggestions: 'Close Suggestions',
    placeholder: 'Enter the player move or line to run the next turn...',
    running: 'Running turn...',
    send: 'Run Turn',
    suggestions: 'Reply Suggestions',
    suggestionsDescription: 'When enabled, new reply suggestions are generated after each completed turn.',
    suggestionsEmpty: 'No reply suggestions yet.',
    suggestionsGenerate: 'Generate Reply Suggestions',
    suggestionsLoading: 'Generating reply suggestions...',
    suggestionsUnavailable: 'Reply suggestions are unavailable while a turn is running.',
  },
  createSession: {
    apiGroup: 'API Group',
    apiGroupPlaceholder: 'Choose an API group',
    cancel: 'Cancel',
    configureApis: 'Open API Management',
    configureApiGroups: 'Open API Management',
    configurePresets: 'Open Presets',
    create: 'Create Session',
    creating: 'Creating...',
    displayName: 'Session Name',
    emptyApis: 'No reusable APIs are available yet. Create at least one connection before starting a session.',
    emptyApiGroups: 'No API groups are available yet. Bind your APIs into a reusable group first.',
    emptyPlayerProfiles: 'No player profiles are available yet. You can still create a blank session.',
    emptyPresets: 'No presets are available yet. Create a preset before starting a session.',
    emptyStories: 'No stories are available yet. Generate a story in the workspace first.',
    playerProfile: 'Player Profile',
    preset: 'Preset',
    presetPlaceholder: 'Choose a preset',
    story: 'Story',
    title: 'Start Session',
  },
  deleteSession: {
    confirm: 'Delete Session',
    deleting: 'Deleting...',
    message: 'Delete this session? This action cannot be undone.',
    title: 'Delete Session',
  },
  editSession: 'Edit Session',
  empty: {
    stage: 'Pick a session from the left, or start a new one.',
  },
  intro: {
    collapse: 'Collapse',
    empty: 'This story does not have an introduction yet.',
    expand: 'Expand',
    section: 'Current Story',
  },
  commonVariables: {
    empty: 'No common variables are available for this story yet.',
    section: 'Variables',
  },
  list: {
    empty: 'No sessions yet.',
    refresh: 'Refresh Sessions',
    section: 'Sessions',
    subtitle: 'Switch or start sessions.',
    untitledStory: 'Untitled story',
  },
  messages: {
    action: 'Action',
    cancelEditPlayer: 'Cancel',
    deletePlayer: 'Delete message',
    editPlayer: 'Edit message',
    expandThought: 'View thought',
    narrator: 'Narrator',
    noMessages: 'This session has no history yet.',
    player: 'Player',
    savePlayer: 'Save',
    thinking: 'Thought',
  },
  notice: {
    apiResourcesFailed: 'Failed to load the API resources.',
    createFailed: 'Failed to create the session.',
    created: 'Session created.',
    deleteFailed: 'Failed to delete the session.',
    deleted: 'Session deleted.',
    listFailed: 'Failed to load sessions.',
    messageDeleteFailed: 'Failed to delete the message.',
    messageUpdateFailed: 'Failed to save the message edit.',
    playerDescriptionFailed: 'Failed to save the player description.',
    playerDescriptionSaved: 'Player description updated.',
    playerProfilesFailed: 'Failed to load player profiles.',
    playerProfileFailed: 'Failed to update the player profile.',
    playerProfileSaved: 'Player profile updated.',
    runFailed: 'Failed to run the turn.',
    sessionCharacterDeleteFailed: 'Failed to delete the temporary character.',
    sessionCharacterEnterFailed: 'Failed to enter the character into the scene.',
    sessionCharacterLeaveFailed: 'Failed to remove the character from the scene.',
    sessionCharacterLoadFailed: 'Failed to load temporary characters.',
    sessionCharacterSaved: 'Temporary character updated.',
    sessionCharacterUpdateFailed: 'Failed to save the temporary character.',
    sessionConfigSaved: 'Session settings updated.',
    sessionLoadFailed: 'Failed to load the session.',
    sessionRenameFailed: 'Failed to rename the session.',
    sessionRenamed: 'Session name updated.',
    snapshotRefreshFailed: 'Failed to refresh the runtime snapshot.',
    snapshotRefreshed: 'Runtime snapshot refreshed.',
    storiesFailed: 'Failed to load stories.',
    suggestRepliesFailed: 'Failed to generate reply suggestions.',
    updateConfigFailed: 'Failed to save the session settings.',
  },
  rail: {
    cast: 'Show Cast',
    intro: 'Show Story',
    status: 'Show Status',
    subtitle: 'Story, node, and cast status.',
    variables: 'Show Variables',
  },
  renameSession: {
    cancel: 'Cancel',
    displayName: 'Session Name',
    errors: {
      displayNameRequired: 'Session name is required.',
    },
    placeholder: 'Updated session name',
    save: 'Save Name',
    saving: 'Saving...',
    sessionId: 'Session ID',
    title: 'Rename Session',
  },
  settings: {
    bindings: {
      apiGroup: 'API Group',
      apiGroupPlaceholder: 'Choose an API group',
      currentApiGroup: 'Current API Group',
      currentPreset: 'Current Preset',
      description: 'Bind one executable API group and one generation preset to this session.',
      errors: {
        apiGroupRequired: 'Choose an API group first.',
        presetRequired: 'Choose a preset first.',
      },
      missing: 'Missing, choose again',
      preset: 'Preset',
      presetPlaceholder: 'Choose a preset',
      save: 'Save Session Settings',
      saving: 'Saving...',
      section: 'Session Bindings',
    },
    description: 'Adjust the current session API group, preset, player profile, and runtime snapshot.',
    playerDescription: {
      description: 'Override the active player description for this session and clear the linked player profile.',
      errors: {
        required: 'Player description is required.',
      },
      placeholder: 'Enter the player description for this session...',
      save: 'Save Player Description',
      saving: 'Saving...',
      section: 'Player Description',
    },
    playerProfile: {
      description: 'Switch the active player profile for this session. This does not change player_state.',
      label: 'Player Profile',
      noProfile: 'No player profile',
      noProfileHint: 'No player profile is currently linked. The session uses a manual player description.',
      placeholder: 'Choose a player profile',
      preview: 'Profile Summary',
      save: 'Apply Player Profile',
      saving: 'Applying...',
      section: 'Player Profile',
    },
    sessionCharacters: {
      delete: 'Delete',
      description: 'Manage runtime-only characters introduced for this session.',
      empty: 'No temporary characters exist in this session yet.',
      enterScene: 'Enter Scene',
      inScene: 'In Scene',
      leaveScene: 'Leave Scene',
      outOfScene: 'Out of Scene',
      section: 'Temporary Characters',
      view: 'View / Edit',
    },
    snapshot: {
      activeCharacters: 'Active Characters',
      currentNode: 'Current Node',
      description: 'Refresh the latest runtime snapshot to confirm the session state.',
      playerDescription: 'Current Player Description',
      playerStateKeys: 'Player State Keys',
      refresh: 'Refresh Snapshot',
      section: 'Runtime Snapshot',
      turnIndex: 'Current Turn',
    },
    title: 'Session Settings',
  },
  stage: {
    subtitle: 'Pick or start a session.',
    title: 'Stage',
  },
  statusBar: {
    actor: '{name} is replying',
    director: 'Director is arranging the turn',
    narrator: 'Narrator is composing the scene',
    recordingInput: 'Keeper is recording the input',
    suggestingReplies: 'Replyer is drafting suggestions',
    updatingState: 'Keeper is syncing the state',
  },
  storyNode: {
    collapse: 'Collapse',
    expand: 'View More',
    goal: 'Current Goal',
    nodeId: 'Node ID',
    scene: 'Current Scene',
    section: 'Status',
  },
  tabs: {
    dialogue: 'Dialogue',
    settings: 'Settings',
    variables: 'Variables',
  },
  time: {
    unknown: 'No timestamp',
  },
  variables: {
    addCharacterGroup: 'Add Character Variables',
    addRow: 'Add Variable',
    characterHint: 'Character ID',
    characterState: 'Character State',
    conditions: {
      currentValue: 'Current Value',
      empty: 'The current node has no outgoing transitions.',
      invalid: 'This condition cannot be rendered yet.',
      missing: 'Missing',
      noCondition: 'Unconditional',
      scopeCharacter: 'Character State',
      scopeCustom: 'Custom State',
      scopePlayer: 'Player State',
      section: 'Node Transition Conditions',
      satisfied: 'Satisfied',
      target: 'Target Node',
      unsatisfied: 'Unsatisfied',
    },
    custom: 'Custom State',
    empty: 'Select a session from the left before inspecting variables.',
    errors: {
      duplicateKey: 'Variable keys must be unique.',
      invalidJson: 'Enter valid JSON.',
      keyRequired: 'Variable key is required.',
    },
    hasExternalUpdates: 'Runtime state changed while you were editing. Refresh variables when you are ready.',
    json: 'Value (JSON)',
    key: 'Key',
    operator: 'Operator',
    playerState: 'Player State',
    refresh: 'Refresh Variables',
    reset: 'Reset Changes',
    save: 'Save Changes',
    saved: 'Variables updated.',
    saveFailed: 'Failed to update variables.',
    saving: 'Saving...',
    sectionDescription: 'Inspect the custom and player state for this session, then verify the node transition conditions.',
    title: 'Variables',
    value: 'Expected Value',
    variableLoadFailed: 'Failed to load variables.',
  },
} as const

export function getStageCopy(language: string) {
  return language.startsWith('zh') ? zh : en
}
