export type StageCopy = ReturnType<typeof getStageCopy>

const zh = {
  apiPanel: {
    effective: '当前生效',
    emptyApis: '还没有可用的 API，当前只能查看会话配置。',
    mode: '会话 API 模式',
    modeOptions: {
      useGlobal: '跟随全局',
      useSession: '会话自定义',
    },
    roles: {
      actor_api_id: '演员',
      architect_api_id: '架构师',
      director_api_id: '导演',
      keeper_api_id: '守秘人',
      narrator_api_id: '叙述者',
      planner_api_id: '规划师',
      replyer_api_id: '回复者',
    },
    save: '保存配置',
    saving: '正在保存...',
    session: '会话 API',
    title: 'Session API',
  },
  cast: {
    active: '当前回复',
    empty: '当前没有激活角色。',
    section: '当前参与角色',
  },
  composer: {
    backToInput: '返回输入',
    placeholder: '输入玩家行动或对白，发起下一轮...',
    running: '正在演出...',
    send: '发起回合',
    suggestions: '回复建议',
    suggestionsDescription: '让回复者先给出几条可选回复，再挑一条回填到输入框。',
    suggestionsEmpty: '还没有回复建议。',
    suggestionsGenerate: '生成回复建议',
    suggestionsLoading: '正在生成回复建议...',
    suggestionsUnavailable: '本回合进行中，暂时不能生成回复建议。',
    suggestionsUse: '采用这条回复',
  },
  createSession: {
    cancel: '取消',
    configMode: '配置模式',
    create: '创建会话',
    creating: '正在创建...',
    defaultLlmFallback: '当前没有已存储 API，本场会话会直接使用默认 LLM 配置。',
    displayName: '会话名称',
    emptyApis: '当前没有可用 API，不能创建自定义会话配置。',
    emptyPlayerProfiles: '当前没有玩家档案，可直接创建空档案会话。',
    emptyStories: '还没有可用的故事，请先在工作台生成故事。',
    playerProfile: '玩家档案',
    sessionApi: '会话 API',
    story: '故事',
    title: '新建会话',
  },
  deleteSession: {
    confirm: '删除会话',
    deleting: '正在删除...',
    message: '确定要删除这场会话吗？这个操作不能撤回。',
    title: '删除会话',
  },
  editSession: '编辑会话',
  empty: {
    stage: '从左侧选择一场会话，或者直接新建一场。',
  },
  intro: {
    collapse: '收起介绍',
    empty: '当前故事还没有介绍。',
    expand: '展开介绍',
    section: '当前 story 介绍',
  },
  list: {
    empty: '还没有会话。',
    refresh: '刷新会话',
    section: '会话列表',
    subtitle: '切换与新建会话。',
    untitledStory: '未命名故事',
  },
  messages: {
    action: '动作',
    cancelEditPlayer: '取消',
    deletePlayer: '删除这条输入',
    editPlayer: '编辑这条输入',
    expandThought: '查看思考',
    narrator: '旁白',
    noMessages: '这场会话还没有历史记录。',
    player: '玩家',
    savePlayer: '保存修改',
    thinking: '思考',
  },
  notice: {
    createFailed: '创建会话失败。',
    created: '会话已创建。',
    deleteFailed: '删除会话失败。',
    deleted: '会话已删除。',
    listFailed: '加载会话列表失败。',
    playerDescriptionFailed: '保存玩家描述失败。',
    playerDescriptionSaved: '玩家描述已更新。',
    playerProfilesFailed: '加载玩家档案失败。',
    playerProfileFailed: '切换玩家档案失败。',
    playerProfileSaved: '玩家档案已更新。',
    suggestRepliesFailed: '生成回复建议失败。',
    messageDeleteFailed: '删除消息失败。',
    messageUpdateFailed: '保存消息修改失败。',
    runFailed: '发起回合失败。',
    sessionConfigSaved: '会话 API 配置已更新。',
    sessionLoadFailed: '加载会话详情失败。',
    sessionRenameFailed: '修改会话名称失败。',
    sessionRenamed: '会话名称已更新。',
    snapshotRefreshFailed: '刷新运行时快照失败。',
    snapshotRefreshed: '运行时快照已刷新。',
    storiesFailed: '加载故事列表失败。',
    updateConfigFailed: '保存会话 API 配置失败。',
  },
  renameSession: {
    cancel: '取消',
    displayName: '会话名称',
    errors: {
      displayNameRequired: '请填写会话名称。',
    },
    placeholder: '新的会话名称',
    save: '保存名称',
    saving: '正在保存...',
    sessionId: '会话 ID',
    title: '修改会话名称',
  },
  settings: {
    api: {
      defaultLlmFallback: '当前没有已存储 API，本场会话会直接使用默认 LLM 配置。',
      description: '调整当前会话采用的 API 组合，决定各个 agent 的执行来源。',
      effective: '当前生效',
      empty: '当前没有可用 API，暂时不能保存会话自定义配置。',
      modeOptions: {
        useGlobal: '跟随全局',
        useSession: '会话自定义',
      },
      roles: {
        actor_api_id: '演员',
        architect_api_id: '架构师',
        director_api_id: '导演',
        keeper_api_id: '守秘人',
        narrator_api_id: '叙述者',
        planner_api_id: '规划师',
        replyer_api_id: '回复者',
      },
      save: '保存 API 配置',
      saving: '正在保存...',
      section: '会话 API',
      selectPlaceholder: '选择一个 API',
      usingGlobal: '当前会话正在跟随全局 API 配置。',
    },
    description: '在这里调整当前会话的 API、玩家档案和运行时状态。',
    playerDescription: {
      description: '直接覆盖当前会话使用的玩家描述，并清空当前玩家档案绑定。',
      errors: {
        required: '请填写玩家描述。',
      },
      placeholder: '输入当前会话要使用的玩家描述...',
      save: '保存玩家描述',
      saving: '正在保存...',
      section: '玩家描述',
    },
    playerProfile: {
      description: '切换当前会话绑定的玩家档案。切换不会改变已有 player_state。',
      label: '玩家档案',
      noProfile: '不绑定玩家档案',
      noProfileHint: '当前未绑定玩家档案，会直接使用手动玩家描述。',
      placeholder: '选择一个玩家档案',
      preview: '当前档案说明',
      save: '应用玩家档案',
      saving: '正在应用...',
      section: '玩家档案',
    },
    snapshot: {
      activeCharacters: '激活角色',
      currentNode: '当前节点',
      description: '读取当前会话最新的运行时快照，确认玩家描述和状态是否已经同步。',
      playerDescription: '当前玩家描述',
      playerStateKeys: '玩家状态字段',
      refresh: '刷新快照',
      section: '运行时快照',
      turnIndex: '当前回合',
    },
    title: '会话设置',
  },
  stage: {
    subtitle: '选择或新建会话。',
    title: '舞台',
  },
  statusBar: {
    actor: '{name} 正在回复',
    director: '导演正在安排演出',
    narrator: '叙述者正在组织旁白',
    recordingInput: '守秘人正在记录输入',
    suggestingReplies: '回复者正在生成建议',
    updatingState: '守秘人正在同步状态',
  },
  rail: {
    subtitle: 'story、状态与角色。',
  },
  storyNode: {
    collapse: '收起详情',
    expand: '查看全部',
    goal: '当前目标',
    nodeId: '节点 ID',
    scene: '当前场景',
    section: '当前对话状态',
  },
  tabs: {
    api: '会话设置',
    session: '会话面板',
  },
  time: {
    unknown: '未记录时间',
  },
} as const

const en = {
  apiPanel: {
    effective: 'Effective',
    emptyApis: 'No APIs are available yet, so this panel is currently read-only.',
    mode: 'Session API Mode',
    modeOptions: {
      useGlobal: 'Use Global',
      useSession: 'Use Session',
    },
    roles: {
      actor_api_id: 'Actor',
      architect_api_id: 'Architect',
      director_api_id: 'Director',
      keeper_api_id: 'Keeper',
      narrator_api_id: 'Narrator',
      planner_api_id: 'Planner',
      replyer_api_id: 'Replyer',
    },
    save: 'Save Config',
    saving: 'Saving...',
    session: 'Session API',
    title: 'Session API',
  },
  cast: {
    active: 'Replying now',
    empty: 'No active cast is available right now.',
    section: 'Active Cast',
  },
  composer: {
    backToInput: 'Back to Input',
    placeholder: 'Enter the player move or line to run the next turn...',
    running: 'Running turn...',
    send: 'Run Turn',
    suggestions: 'Reply Suggestions',
    suggestionsDescription: 'Let the replyer draft a few player replies, then bring one back into the input box.',
    suggestionsEmpty: 'No reply suggestions yet.',
    suggestionsGenerate: 'Generate Suggestions',
    suggestionsLoading: 'Generating reply suggestions...',
    suggestionsUnavailable: 'Reply suggestions are unavailable while a turn is running.',
    suggestionsUse: 'Use Suggestion',
  },
  createSession: {
    cancel: 'Cancel',
    configMode: 'Config Mode',
    create: 'Create Session',
    creating: 'Creating...',
    defaultLlmFallback: 'No stored APIs are available, so this session will use the default LLM config directly.',
    displayName: 'Session Name',
    emptyApis: 'No APIs are available, so a custom session config cannot be created yet.',
    emptyPlayerProfiles: 'No player profiles are available yet. You can still create a blank session.',
    emptyStories: 'No stories are available yet. Generate a story in the workspace first.',
    playerProfile: 'Player Profile',
    sessionApi: 'Session API',
    story: 'Story',
    title: 'Start Session',
  },
  deleteSession: {
    confirm: 'Delete Session',
    deleting: 'Deleting...',
    message: 'Delete this session? This cannot be undone.',
    title: 'Delete Session',
  },
  editSession: 'Edit Session',
  empty: {
    stage: 'Pick a session from the left, or start a new one.',
  },
  intro: {
    collapse: 'Collapse',
    empty: 'This story does not have an introduction yet.',
    expand: 'Expand',
    section: 'Current Story',
  },
  list: {
    empty: 'No sessions yet.',
    refresh: 'Refresh Sessions',
    section: 'Sessions',
    subtitle: 'Switch or start sessions.',
    untitledStory: 'Untitled story',
  },
  messages: {
    action: 'Action',
    cancelEditPlayer: 'Cancel',
    deletePlayer: 'Delete message',
    editPlayer: 'Edit message',
    expandThought: 'View thought',
    narrator: 'Narrator',
    noMessages: 'This session has no history yet.',
    player: 'Player',
    savePlayer: 'Save',
    thinking: 'Thought',
  },
  notice: {
    createFailed: 'Failed to create the session.',
    created: 'Session created.',
    deleteFailed: 'Failed to delete the session.',
    deleted: 'Session deleted.',
    listFailed: 'Failed to load sessions.',
    playerDescriptionFailed: 'Failed to save the player description.',
    playerDescriptionSaved: 'Player description updated.',
    playerProfilesFailed: 'Failed to load player profiles.',
    playerProfileFailed: 'Failed to update the player profile.',
    playerProfileSaved: 'Player profile updated.',
    suggestRepliesFailed: 'Failed to generate reply suggestions.',
    messageDeleteFailed: 'Failed to delete the message.',
    messageUpdateFailed: 'Failed to save the message edit.',
    runFailed: 'Failed to run the turn.',
    sessionConfigSaved: 'Session API config updated.',
    sessionLoadFailed: 'Failed to load the session.',
    sessionRenameFailed: 'Failed to rename the session.',
    sessionRenamed: 'Session name updated.',
    snapshotRefreshFailed: 'Failed to refresh the runtime snapshot.',
    snapshotRefreshed: 'Runtime snapshot refreshed.',
    storiesFailed: 'Failed to load stories.',
    updateConfigFailed: 'Failed to save the session API config.',
  },
  renameSession: {
    cancel: 'Cancel',
    displayName: 'Session Name',
    errors: {
      displayNameRequired: 'Session name is required.',
    },
    placeholder: 'Updated session name',
    save: 'Save Name',
    saving: 'Saving...',
    sessionId: 'Session ID',
    title: 'Rename Session',
  },
  settings: {
    api: {
      defaultLlmFallback: 'No stored APIs are available, so this session will use the default LLM config directly.',
      description: 'Adjust which APIs the current session uses for each agent role.',
      effective: 'Effective',
      empty: 'No APIs are available yet, so a session-specific API setup cannot be saved.',
      modeOptions: {
        useGlobal: 'Use Global',
        useSession: 'Use Session',
      },
      roles: {
        actor_api_id: 'Actor',
        architect_api_id: 'Architect',
        director_api_id: 'Director',
        keeper_api_id: 'Keeper',
        narrator_api_id: 'Narrator',
        planner_api_id: 'Planner',
        replyer_api_id: 'Replyer',
      },
      save: 'Save API Config',
      saving: 'Saving...',
      section: 'Session API',
      selectPlaceholder: 'Choose an API',
      usingGlobal: 'This session currently follows the global API assignment.',
    },
    description: 'Adjust the current session API setup, player profile, and runtime snapshot here.',
    playerDescription: {
      description: 'Override the active player description for this session and clear the linked player profile.',
      errors: {
        required: 'Player description is required.',
      },
      placeholder: 'Enter the player description for this session...',
      save: 'Save Player Description',
      saving: 'Saving...',
      section: 'Player Description',
    },
    playerProfile: {
      description: 'Switch the active player profile for this session. This does not change player_state.',
      label: 'Player Profile',
      noProfile: 'No player profile',
      noProfileHint: 'No player profile is currently linked. The session uses a manual player description.',
      placeholder: 'Choose a player profile',
      preview: 'Profile Summary',
      save: 'Apply Player Profile',
      saving: 'Applying...',
      section: 'Player Profile',
    },
    snapshot: {
      activeCharacters: 'Active Characters',
      currentNode: 'Current Node',
      description: 'Refresh the latest runtime snapshot to confirm the session state and player description.',
      playerDescription: 'Current Player Description',
      playerStateKeys: 'Player State Keys',
      refresh: 'Refresh Snapshot',
      section: 'Runtime Snapshot',
      turnIndex: 'Current Turn',
    },
    title: 'Session Settings',
  },
  stage: {
    subtitle: 'Pick or start a session.',
    title: 'Stage',
  },
  statusBar: {
    actor: '{name} is replying',
    director: 'Director is arranging the turn',
    narrator: 'Narrator is composing the scene',
    recordingInput: 'Keeper is recording the input',
    suggestingReplies: 'Replyer is drafting suggestions',
    updatingState: 'Keeper is syncing the state',
  },
  rail: {
    subtitle: 'Story, node, and cast status.',
  },
  storyNode: {
    collapse: 'Collapse',
    expand: 'View all',
    goal: 'Current Goal',
    nodeId: 'Node ID',
    scene: 'Current Scene',
    section: 'Current Beat',
  },
  tabs: {
    api: 'Session Settings',
    session: 'Session Panel',
  },
  time: {
    unknown: 'No timestamp',
  },
} as const

export function getStageCopy(language: string) {
  return language.startsWith('zh') ? zh : en
}
